services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ywy20010917.
      MYSQL_DATABASE: help_bitcoin
      MYSQL_USER: caitlynn
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./bitcoin_data_ingestion
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3030:3030"

  frontend:
    build:
      context: ./bitcoin_ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
